### ISSUE TITLE
Add firewall as resource

### ISSUE THREAD

**Issue by aleksijohansson** [vtorhonen/terraform-provider-upcloud#15]
It seems the only "resource" in UpCloud that can currently be managed is a server, firewalls are not yet included in this provider? I think this is one of the use cases for using Terraform in the first place since firewall rules can be large and complex and they are very important to get right.

**Comment by vtorhonen** [comment]
UpCloud firewall rules can be managed through their API and those API calls are also implemented in their Go library. Therefore it should be fairly straightforward to implement a Terraform resource. Contributions welcome.

Relevant links:

- https://www.upcloud.com/api/11-firewall/
- https://github.com/UpCloudLtd/upcloud-go-api/blob/master/upcloud/request/firewall.go

**Comment by vtorhonen** [comment]
Firewall rule resource added in #21. You can now define your own firewall rules as follows:

```
resource "upcloud_server" "test" {
    ...
    firewall = "true"
    ...
}

// Allow incoming SSH
resource "upcloud_firewall_rule" "allow_ssh" {
  server_id              = "${upcloud_server.test.id}"
  direction              = "in"
  action                 = "accept"
  position               = "1"
  family                 = "IPv4"
  destination_port_start = "22"
  destination_port_end   = "22"
}

// Deny everything else
resource "upcloud_firewall_rule" "deny_all" {
  server_id = "${upcloud_server.test.id}"
  direction = "in"
  action    = "drop"
  position  = "2"
  family    = "IPv4"
}
```

Probably worth mentioning that DNS traffic to UpCloud DNS server needs to be allowed separately, as mentioned on their control panel:

> Please note that DNS traffic must also be explicitly allowed. Our DNS servers are 94.237.127.9 and 94.237.40.9 (in IPv6 network 2a04:3540:53::1 and 2a04:3544:53::1). Incoming TCP and UDP traffic from source port 53 must be allowed from these hosts.

Also worth mentioning that by default IPv6 is enabled and separate firewall rules should be implemented for that as well. You can also disable IPv6 by setting `ipv6 = "false"` on the server resource.
