### ISSUE TITLE
Output the IP of a created server resource

### ISSUE THREAD

**Issue by aleksijohansson** [vtorhonen/terraform-provider-upcloud#18]
Currently when creating a server resource with this provider it only outputs the ID of the server when it's created, but no information that would allow connecting to the created resource. I think it would be good to output the needed information after the creation so that one does not have to still have to open the UpCloud UI to get information like the IP of the created server. Outputting this info allows for automation where `terraform apply` could be run in a script that captures the IP and continues the configuration automatically. The example documentation here https://github.com/vtorhonen/terraform-provider-upcloud/blob/master/examples/README.md suggests this would happen. When testing the tool this part never showed up:
```
Outputs:

ip = <SOME IP ADDRESS>
```

**Comment by vtorhonen** [comment]
Thanks. Fixed in #19.

You can also use `terraform state show upcloud_server.test` to print out all stored fields from the state file for that resource.

**Comment by aleksijohansson** [comment]
@vtorhonen Thanks for instructing the noob here.
